<?php

namespace App\Support\Billing;

/**
 * All invoice line types currently produced by the billing system.
 *
 * `ClientInvoiceLine::type` is stored as a string column. This enum names
 * known values and the subsets used by billing calculations.
 */
enum InvoiceLineType: string
{
    case Retainer = 'retainer';
    case PriorMonthRetainer = 'prior_month_retainer';
    case PriorMonthBillable = 'prior_month_billable';
    case AdditionalHours = 'additional_hours';
    case Credit = 'credit';
    case Expense = 'expense';
    case Milestone = 'milestone';
    case Adjustment = 'adjustment';
    case RecurringItem = 'recurring_item';
    case Reconciliation = 'reconciliation';
    case Subcontractor = 'subcontractor';
    // Settle re-carried deferred work (see CarriedDeferredLine). Their type is
    // their identity - the ledger reads nothing else - so no manual line may
    // carry either (see systemOnlyValues()).
    case CarriedDeferredApplied = 'carried_deferred_applied';
    case CarriedDeferredBilled = 'carried_deferred_billed';
    // An explicit hourly settlement consumes none of the retainer's capacity.
    // Reserved for the forthcoming buy-down writer; manual input is refused.
    case DeferredBuyDown = 'deferred_buydown';

    /** @return list<string> */
    public static function settledOutsideRetainerValues(): array
    {
        return array_values(array_map(
            static fn (self $type): string => $type->value,
            array_filter(self::cases(), static fn (self $type): bool => DeferredWorkDisposition::fromAllocation($type->value) === DeferredWorkDisposition::SettledOutsideRetainer),
        ));
    }

    /**
     * Line types generated by the invoicing service.
     *
     * These are safe to wipe + regenerate on a draft invoice; manual
     * `Adjustment` lines are always preserved.
     *
     * @return list<string>
     */
    public static function systemGeneratedValues(): array
    {
        return [
            self::Retainer->value,
            self::PriorMonthRetainer->value,
            self::PriorMonthBillable->value,
            self::AdditionalHours->value,
            self::Credit->value,
            self::Milestone->value,
            self::RecurringItem->value,
            self::Reconciliation->value,
            self::Subcontractor->value,
            self::CarriedDeferredApplied->value,
            self::CarriedDeferredBilled->value,
        ];
    }

    /**
     * Types only billing code may write, because it turns them back into
     * money state by type alone, so every manual door refuses them (#349):
     * - carried-deferred lines would settle, or mark billed, deferred work
     *   nobody applied;
     * - a credit line spends the client's overpayment credit pool at issue;
     * - an expense line reads as a billed expense with no claim behind it;
     * - the retainer, prior-month and additional-hours lines are the
     *   generator's wording, read back by the cycle-sold, capacity and
     *   overage code.
     *
     * The generators write these directly, never through a manual door, and
     * a generated draft is not edited through one: the agent update accepts
     * only an ad-hoc draft. Production held none of these on a manual invoice
     * when they were refused.
     *
     * @return list<string>
     */
    public static function systemOnlyValues(): array
    {
        return [
            self::CarriedDeferredApplied->value,
            self::CarriedDeferredBilled->value,
            self::DeferredBuyDown->value,
            self::Credit->value,
            self::Expense->value,
            self::Retainer->value,
            self::PriorMonthRetainer->value,
            self::PriorMonthBillable->value,
            self::AdditionalHours->value,
        ];
    }

    /**
     * Line types whose date says when the work happened.
     *
     * An invoice's service period is the window of work it reconciles, and it is
     * widened to cover these lines. The rest are charges for a period that has
     * not happened yet - the retainer being sold, a recurring item for the month
     * ahead - and their dates sit in the *next* month by design.
     *
     * This was a denylist naming retainer and credit, so recurring items pushed
     * the service period a month forward. The overlap guard then refused to
     * generate that month, for good, and the failure was swallowed into
     * `skipped`: a client silently stopped being invoiced.
     *
     * An allowlist is the safer shape here. A new line type that describes work
     * shows up as a period that is too narrow, which is visible; under a
     * denylist it lands as a period too wide, which stops billing.
     *
     * @return list<string>
     */
    public static function definingTheWorkPeriod(): array
    {
        return [
            self::PriorMonthRetainer->value,
            self::PriorMonthBillable->value,
            self::AdditionalHours->value,
            self::Milestone->value,
            self::Expense->value,
            self::Subcontractor->value,
            self::Reconciliation->value,
            self::Adjustment->value,
            self::CarriedDeferredApplied->value,
            self::CarriedDeferredBilled->value,
            self::DeferredBuyDown->value,
        ];
    }

    /**
     * The complement: charges for a period yet to come.
     *
     * @return list<string>
     */
    public static function billedInAdvance(): array
    {
        return array_values(array_diff(
            array_map(static fn (self $case): string => $case->value, self::cases()),
            self::definingTheWorkPeriod(),
        ));
    }
}
