<?php

namespace App\Support\Billing;

/**
 * All invoice line types currently produced by the billing system.
 *
 * `ClientInvoiceLine::line_type` is still stored as a string column so
 * third-party integrations don't break; this enum provides a compile-time
 * checked mirror for new code paths (deferred billing, overpayment credits,
 * etc.).
 */
enum InvoiceLineType: string
{
    case Retainer = 'retainer';
    case PriorMonthRetainer = 'prior_month_retainer';
    case PriorMonthBillable = 'prior_month_billable';
    case AdditionalHours = 'additional_hours';
    case Credit = 'credit';
    case Expense = 'expense';
    case Milestone = 'milestone';
    case Adjustment = 'adjustment';
    case RecurringItem = 'recurring_item';
    case Reconciliation = 'reconciliation';
    case Subcontractor = 'subcontractor';

    /**
     * Line types generated by the invoicing service.
     *
     * These are safe to wipe + regenerate on a draft invoice; manual
     * `Adjustment` lines are always preserved.
     *
     * @return list<string>
     */
    public static function systemGeneratedValues(): array
    {
        return [
            self::Retainer->value,
            self::PriorMonthRetainer->value,
            self::PriorMonthBillable->value,
            self::AdditionalHours->value,
            self::Credit->value,
            self::Milestone->value,
            self::RecurringItem->value,
            self::Reconciliation->value,
            self::Subcontractor->value,
        ];
    }
}
