<?php

namespace App\Support\Billing;

/**
 * All invoice line types currently produced by the billing system.
 *
 * `ClientInvoiceLine::type` is stored as a string column. This enum names
 * known values and the subsets used by billing calculations.
 */
enum InvoiceLineType: string
{
    case Retainer = 'retainer';
    case PriorMonthRetainer = 'prior_month_retainer';
    case PriorMonthBillable = 'prior_month_billable';
    case AdditionalHours = 'additional_hours';
    case Credit = 'credit';
    case Expense = 'expense';
    case Milestone = 'milestone';
    case Adjustment = 'adjustment';
    case RecurringItem = 'recurring_item';
    case Reconciliation = 'reconciliation';
    case Subcontractor = 'subcontractor';
    // Settle re-carried deferred work (see CarriedDeferredLine). Their type is
    // their identity - the ledger reads nothing else - so no manual line may
    // carry either (see systemOnlyValues()).
    case CarriedDeferredApplied = 'carried_deferred_applied';
    case CarriedDeferredBilled = 'carried_deferred_billed';

    /**
     * Line types generated by the invoicing service.
     *
     * These are safe to wipe + regenerate on a draft invoice; manual
     * `Adjustment` lines are always preserved.
     *
     * @return list<string>
     */
    public static function systemGeneratedValues(): array
    {
        return [
            self::Retainer->value,
            self::PriorMonthRetainer->value,
            self::PriorMonthBillable->value,
            self::AdditionalHours->value,
            self::Credit->value,
            self::Milestone->value,
            self::RecurringItem->value,
            self::Reconciliation->value,
            self::Subcontractor->value,
            self::CarriedDeferredApplied->value,
            self::CarriedDeferredBilled->value,
        ];
    }

    /**
     * Types only billing code may write, because it turns them back into
     * money state by type alone. A manual carried-deferred line would settle,
     * or mark billed, deferred work nobody applied; a manual credit line would
     * spend the client's overpayment credit pool at issue with nothing
     * reconciling it; a manual expense line would read as a billed expense
     * with no claim behind it (#349). The generators write these directly,
     * never through a manual door, and a generated expense line's claim
     * already stops its draft's lines being replaced.
     *
     * @return list<string>
     */
    public static function systemOnlyValues(): array
    {
        return [
            self::CarriedDeferredApplied->value,
            self::CarriedDeferredBilled->value,
            self::Credit->value,
            self::Expense->value,
        ];
    }

    /**
     * Types the generator words and the capacity and overage code reads back:
     * refused on a new manual line, but kept when a draft that already
     * carries one is saved again (#349).
     *
     * The agent update replaces every line of a draft, generated ones
     * included, so refusing these outright would stop an agent editing a
     * generated cadence draft at all. A draft that did not carry the type
     * cannot gain it by hand.
     *
     * @return list<string>
     */
    public static function generatorOwnedValues(): array
    {
        return [
            self::Retainer->value,
            self::PriorMonthRetainer->value,
            self::AdditionalHours->value,
        ];
    }

    /**
     * Every type a manual line on a new invoice or template may not carry.
     *
     * @return list<string>
     */
    public static function manuallyRefusedValues(): array
    {
        return [...self::systemOnlyValues(), ...self::generatorOwnedValues()];
    }

    /**
     * Line types whose date says when the work happened.
     *
     * An invoice's service period is the window of work it reconciles, and it is
     * widened to cover these lines. The rest are charges for a period that has
     * not happened yet - the retainer being sold, a recurring item for the month
     * ahead - and their dates sit in the *next* month by design.
     *
     * This was a denylist naming retainer and credit, so recurring items pushed
     * the service period a month forward. The overlap guard then refused to
     * generate that month, for good, and the failure was swallowed into
     * `skipped`: a client silently stopped being invoiced.
     *
     * An allowlist is the safer shape here. A new line type that describes work
     * shows up as a period that is too narrow, which is visible; under a
     * denylist it lands as a period too wide, which stops billing.
     *
     * @return list<string>
     */
    public static function definingTheWorkPeriod(): array
    {
        return [
            self::PriorMonthRetainer->value,
            self::PriorMonthBillable->value,
            self::AdditionalHours->value,
            self::Milestone->value,
            self::Expense->value,
            self::Subcontractor->value,
            self::Reconciliation->value,
            self::Adjustment->value,
            self::CarriedDeferredApplied->value,
            self::CarriedDeferredBilled->value,
        ];
    }

    /**
     * The complement: charges for a period yet to come.
     *
     * @return list<string>
     */
    public static function billedInAdvance(): array
    {
        return array_values(array_diff(
            array_map(static fn (self $case): string => $case->value, self::cases()),
            self::definingTheWorkPeriod(),
        ));
    }
}
