/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/workspaces/{workspace_id}/time-entries/{entry_id}/unapprove': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Return approved time to draft as a workspace owner/admin. Draft-invoice allocations are released and the invoice regenerated atomically; issued/paid/void allocations are refused. */
        post: operations['time_entries.unapprove'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/workspaces/{workspace_id}/agreements/{agreement_id}/terminate': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Workspace managers only. Requires both AGENT_API_WRITES_ENABLED and AGENT_API_CLIENT_WRITES_ENABLED. Versioned writes also require the corresponding read scope. Enabling automatic delivery requires a delay and a valid billing email or client portal recipient. Existing records require their current opaque expected_version; agreement creation uses the parent client version. Activation and termination require confirm: true. */
        post: operations['agreements.terminate'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/workspaces/{workspace_id}/agreements/{agreement_id}/activate': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Workspace managers only. Requires both AGENT_API_WRITES_ENABLED and AGENT_API_CLIENT_WRITES_ENABLED. Versioned writes also require the corresponding read scope. Enabling automatic delivery requires a delay and a valid billing email or client portal recipient. Existing records require their current opaque expected_version; agreement creation uses the parent client version. Activation and termination require confirm: true. */
        post: operations['agreements.activate'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/workspaces/{workspace_id}/clients/{client_id}/agreements': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Workspace managers only. Requires both AGENT_API_WRITES_ENABLED and AGENT_API_CLIENT_WRITES_ENABLED. Versioned writes also require the corresponding read scope. Enabling automatic delivery requires a delay and a valid billing email or client portal recipient. Existing records require their current opaque expected_version; agreement creation uses the parent client version. Activation and termination require confirm: true. */
        post: operations['agreements.create'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/workspaces/{workspace_id}/agreements/{agreement_id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['agreements.get'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Workspace managers only. Requires both AGENT_API_WRITES_ENABLED and AGENT_API_CLIENT_WRITES_ENABLED. Versioned writes also require the corresponding read scope. Enabling automatic delivery requires a delay and a valid billing email or client portal recipient. Existing records require their current opaque expected_version; agreement creation uses the parent client version. Activation and termination require confirm: true. */
        patch: operations['agreements.update'];
        trace?: never;
    };
    '/workspaces/{workspace_id}/agreements': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['agreements.list'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/workspaces/{workspace_id}/clients/{client_id}/restore': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Workspace managers only. Requires both AGENT_API_WRITES_ENABLED and AGENT_API_CLIENT_WRITES_ENABLED. Versioned writes also require the corresponding read scope. Enabling automatic delivery requires a delay and a valid billing email or client portal recipient. Existing records require their current opaque expected_version; agreement creation uses the parent client version. Activation and termination require confirm: true. */
        post: operations['clients.restore'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/workspaces/{workspace_id}/clients/{client_id}/archive': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Workspace managers only. Requires both AGENT_API_WRITES_ENABLED and AGENT_API_CLIENT_WRITES_ENABLED. Versioned writes also require the corresponding read scope. Enabling automatic delivery requires a delay and a valid billing email or client portal recipient. Existing records require their current opaque expected_version; agreement creation uses the parent client version. Activation and termination require confirm: true. */
        post: operations['clients.archive'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/workspaces/{workspace_id}/clients/{client_id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['clients.get'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Workspace managers only. Requires both AGENT_API_WRITES_ENABLED and AGENT_API_CLIENT_WRITES_ENABLED. Versioned writes also require the corresponding read scope. Enabling automatic delivery requires a delay and a valid billing email or client portal recipient. Existing records require their current opaque expected_version; agreement creation uses the parent client version. Activation and termination require confirm: true. */
        patch: operations['clients.update'];
        trace?: never;
    };
    '/workspaces/{workspace_id}/clients': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['clients.list'];
        put?: never;
        /** @description Workspace managers only. Requires both AGENT_API_WRITES_ENABLED and AGENT_API_CLIENT_WRITES_ENABLED. Versioned writes also require the corresponding read scope. Enabling automatic delivery requires a delay and a valid billing email or client portal recipient. Existing records require their current opaque expected_version; agreement creation uses the parent client version. Activation and termination require confirm: true. */
        post: operations['clients.create'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/workspaces/{workspace_id}/expenses': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['expenses.list'];
        put?: never;
        /** @description Workspace managers only. Atomic batch of at most 20 expenses; amounts are minor units. Requires both AGENT_API_WRITES_ENABLED and AGENT_API_EXPENSE_WRITES_ENABLED. No approval or receipt attachment. */
        post: operations['expenses.log'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/workspaces/{workspace_id}/expenses/{expense_id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Soft-delete draft expenses only, using the current version. Approved, invoiced and unknown statuses are refused. Workspace managers only; both write flags required. */
        delete: operations['expenses.delete'];
        options?: never;
        head?: never;
        /** @description Replace all draft expense facts using its current version. Omitted project_id preserves attribution; explicit null clears it. Workspace managers only; both expense and workflow write flags required. */
        patch: operations['expenses.update'];
        trace?: never;
    };
    '/workspaces/{workspace_id}/payments': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List received payments for an explicit invoice_id or company_id (at least one required). Invoice visibility applies; private processor and reconciliation data is excluded. */
        get: operations['payments.list'];
        put?: never;
        /** @description Owner/admin bookkeeping for money already received. Never initiates a charge. Explicit invoice, minor-unit amount, currency, payment date and method required; reference is optional. Overpayment refused. Requires both outer workflow and payment write flags. */
        post: operations['payments.record'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/workspaces/{workspace_id}/payments/{payment_id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Owner/admin correction of a received payment's descriptive fields: method, reference and received_on, at least one of which must be given. Requires the version from payments.list and a reason, which is kept in the client history. Omitted fields are unchanged; an explicit null reference clears it. A stale version is refused with 409 and a correction that changes nothing records nothing. Amount, currency, status, refunds, the invoice and processor fields cannot be changed. Never initiates a charge or a refund. Requires both outer workflow and payment write flags. */
        patch: operations['payments.correct'];
        trace?: never;
    };
    '/context': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns role capabilities intersected with the current token scopes and write-cutover state. Per-project capability IDs are included only with projects:read. */
        get: operations['context.get'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/connections/{token}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations['connections.revoke'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/workspaces/{workspace_id}/summary': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Always returns workspace_id; project, time, and invoice sections are omitted unless the token has their corresponding read scope. */
        get: operations['operations.summary'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/workspaces/{workspace_id}/projects': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['projects.list'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/workspaces/{workspace_id}/projects/{project_id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Task data is embedded only when the token also has tasks:read. */
        get: operations['projects.get'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/workspaces/{workspace_id}/projects/{project_id}/tasks': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations['tasks.create'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/workspaces/{workspace_id}/tasks': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['tasks.list'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/workspaces/{workspace_id}/tasks/{task_id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['tasks.get'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Omitted properties remain unchanged; explicit null clears nullable properties. */
        patch: operations['tasks.update'];
        trace?: never;
    };
    '/workspaces/{workspace_id}/time-entries': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['time_entries.list'];
        put?: never;
        post: operations['time_entries.log'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/workspaces/{workspace_id}/time-entries/{entry_id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations['time_entries.delete'];
        options?: never;
        head?: never;
        /** @description Omitted properties remain unchanged; explicit null clears nullable properties. */
        patch: operations['time_entries.update'];
        trace?: never;
    };
    '/workspaces/{workspace_id}/time-entries/approve': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations['time_entries.approve'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/workspaces/{workspace_id}/invoices': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['invoices.list'];
        put?: never;
        post: operations['invoices.create_draft'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/workspaces/{workspace_id}/invoices/{invoice_id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['invoices.get'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Replace the explicit time selection and manual lines on a draft invoice. */
        patch: operations['invoices.update_draft'];
        trace?: never;
    };
    '/workspaces/{workspace_id}/invoices/{invoice_id}/discard': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations['invoices.discard_draft'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/workspaces/{workspace_id}/invoices/{invoice_id}/issue': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations['invoices.issue'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/workspaces/{workspace_id}/invoices/{invoice_id}/send': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations['invoices.send'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/workspaces/{workspace_id}/invoices/{invoice_id}/void': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations['invoices.void'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/workspaces/{workspace_id}/invoices/{invoice_id}/details': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Change the due date and/or notes of any draft invoice, generated or ad hoc, using its current version. Lines, linked time and the hours statement are unchanged, and a generated draft keeps the change when it is regenerated. A due date may not precede the draft's issue date. Issued invoices are corrected with invoices.correct instead. */
        patch: operations['invoices.update_details'];
        trace?: never;
    };
    '/workspaces/{workspace_id}/invoices/{invoice_id}/correct': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Make an audited in-place correction to an unpaid issued invoice that has not been emailed to the client: its due date and/or line wording, and money only on operator-authored lines. Omitted lines are kept as they are; supplied lines must name every existing line. The document revision advances and any automatic client delivery is held for explicit release. Requires explicit user confirmation and a reason kept in the client history. Paid, partially paid, sent and void invoices are refused; void and reissue those instead. */
        post: operations['invoices.correct'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        agreements_terminateRequest: {
            /** @constant */
            confirm: true;
            expected_version: string;
            /** Format: date */
            ends_on?: string | null;
        };
        agreements_activateRequest: {
            /** @constant */
            confirm: true;
            expected_version: string;
        };
        agreements_updateRequest: {
            expected_version: string;
            title?: string;
            /** Format: date */
            starts_on?: string;
            /** Format: date */
            ends_on?: string | null;
            currency?: string;
            /** @enum {string} */
            billing_cadence?:
                'one_time' | 'monthly' | 'quarterly' | 'semi_annual' | 'annual';
            agreement_text?: string | null;
            is_visible_to_client?: boolean;
            hourly_rate_amount?: number | null;
            retainer_amount?: number | null;
            retainer_minutes?: number | null;
            period_retainer_amount?: number | null;
            period_retainer_minutes?: number | null;
            catch_up_threshold_minutes?: number | null;
            rollover_months?: number | null;
            rollover_policy?: string | null;
            /** @enum {string|null} */
            first_cycle_proration?:
                'prorate_hours' | 'full_period' | 'align_next_cycle' | null;
            bill_overage_interim?: boolean | null;
        };
        agreements_createRequest: {
            expected_version: string;
            title: string;
            /** Format: date */
            starts_on: string;
            /** Format: date */
            ends_on?: string | null;
            currency: string;
            /** @enum {string} */
            billing_cadence?:
                'one_time' | 'monthly' | 'quarterly' | 'semi_annual' | 'annual';
            agreement_text?: string | null;
            is_visible_to_client?: boolean;
            hourly_rate_amount?: number | null;
            retainer_amount?: number | null;
            retainer_minutes?: number | null;
        };
        clients_restoreRequest: {
            expected_version: string;
        };
        clients_archiveRequest: {
            expected_version: string;
        };
        clients_updateRequest: {
            expected_version: string;
            name?: string;
            /** Format: email */
            billing_email?: string | null;
            automatic_invoice_email_enabled?: boolean;
            automatic_invoice_email_delay_days?: number | null;
            is_active?: boolean;
        } & unknown;
        clients_createRequest: {
            name: string;
            /** Format: email */
            billing_email?: string | null;
        };
        AgreementListResponse: {
            data: components['schemas']['Agreement'][];
            meta: components['schemas']['PaginationMeta'];
        };
        AgreementResponse: {
            data: components['schemas']['Agreement'];
        };
        ClientCompanyListResponse: {
            data: components['schemas']['ClientCompany'][];
            meta: components['schemas']['PaginationMeta'];
        };
        ClientCompanyResponse: {
            data: components['schemas']['ClientCompany'];
        };
        Agreement: {
            version: string;
            /** Format: uuid */
            id: string;
            title: string;
            status: string;
            currency: string;
            billing_cadence: string | null;
            /** @enum {string|null} */
            effective_billing_cadence:
                'monthly' | 'quarterly' | 'semi_annual' | 'annual' | null;
            /** @enum {string|null} */
            effective_first_cycle_proration:
                'prorate_hours' | 'full_period' | 'align_next_cycle' | null;
            is_recurring: boolean;
            /** Format: date */
            starts_on: string;
            /** Format: date */
            ends_on: string | null;
            /** Format: date-time */
            signed_at: string | null;
            retainer_minutes_per_period: number | null;
            retainer_minutes_per_month: number | null;
            retainer_amount_per_period: number | null;
            hourly_rate_amount: number | null;
            rollover_months: number | null;
            project: string | null;
            /** Format: uuid */
            client_id: string;
            client_name: string;
            /** Format: uuid */
            project_id: string | null;
        };
        ClientCompany: {
            version: string;
            /** Format: uuid */
            id: string;
            name: string;
            billing_email: string | null;
            is_active: boolean;
            automatic_invoice_email_enabled: boolean;
            automatic_invoice_email_delay_days: number | null;
        };
        Expense: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            company_id: string;
            /** Format: uuid */
            project_id: string | null;
            /** Format: date */
            spent_on: string;
            amount: number;
            currency: string;
            description: string;
            status: string;
            status_label: string;
            version: components['schemas']['Version'];
            can_edit: boolean;
            can_delete: boolean;
        };
        ExpenseListResponse: {
            data: components['schemas']['Expense'][];
            meta: components['schemas']['PaginationMeta'];
        };
        ExpenseResponse: {
            data: components['schemas']['Expense'];
        };
        ExpenseBatchResponse: {
            data: components['schemas']['Expense'][];
        };
        ExpenseLogItem: {
            /** Format: uuid */
            company_id: string;
            /** Format: date */
            spent_on: string;
            amount: number;
            currency: string;
            description: string;
            /** Format: uuid */
            project_id?: string | null;
        };
        ExpenseLogRequest: {
            entries: components['schemas']['ExpenseLogItem'][];
        };
        ExpenseUpdateRequest: {
            expected_version: components['schemas']['Version'];
            /** Format: date */
            spent_on: string;
            amount: number;
            currency: string;
            description: string;
            /** Format: uuid */
            project_id?: string | null;
        };
        ReceivedPayment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            invoice_id: string;
            amount: number;
            currency: string;
            /** Format: date */
            received_on: string | null;
            method: string | null;
            reference: string | null;
            status: string;
            refunded_amount: number;
            version: components['schemas']['Version'];
        };
        ReceivedPaymentRecordRequest: {
            /** Format: uuid */
            invoice_id: string;
            amount: number;
            currency: string;
            /** Format: date */
            received_on: string;
            method: string;
            reference?: string | null;
        };
        ReceivedPaymentCorrectionRequest:
            | {
                  expected_version: components['schemas']['Version'];
                  reason: string;
                  method?: string;
                  reference?: string | null;
                  /** Format: date */
                  received_on?: string;
              }
            | unknown
            | unknown
            | unknown;
        ReceivedPaymentResponse: {
            data: components['schemas']['ReceivedPayment'];
        };
        ReceivedPaymentBatchResponse: {
            data: components['schemas']['ReceivedPayment'][];
        };
        ReceivedPaymentListResponse: {
            data: components['schemas']['ReceivedPayment'][];
            next_cursor: string | null;
        };
        Error: {
            message: string;
            errors?: {
                [key: string]: string[];
            };
        };
        /** Format: uuid */
        Uuid: string;
        Version: string;
        Currency: string;
        /** @enum {string} */
        TimeStatus: 'draft' | 'approved' | 'invoiced';
        /** @enum {string} */
        InvoiceStatus: 'draft' | 'issued' | 'partially_paid' | 'paid' | 'void';
        /** @enum {string} */
        LinkedTimeState: 'reserved' | 'consumed' | 'released';
        /** @enum {string} */
        InvoiceKind:
            'cadence_period' | 'interim_overage' | 'terminal' | 'ad_hoc';
        PaginationMeta: {
            next_cursor: string | null;
        };
        WorkspaceContext: {
            id: components['schemas']['Uuid'];
            name: string;
            timezone: string;
            default_currency: components['schemas']['Currency'];
            workspace_role: string | null;
            capabilities: string[];
            project_capabilities: components['schemas']['ProjectCapability'][];
            /** Format: uri */
            web_url: string;
        };
        ProjectCapability: {
            project_id: components['schemas']['Uuid'];
            /** @enum {string} */
            role: 'owner' | 'manager' | 'contributor' | 'viewer' | 'client';
            capabilities: string[];
        };
        Context: {
            id: components['schemas']['Uuid'];
            name: string;
            workspaces: components['schemas']['WorkspaceContext'][];
        };
        ContextResponse: {
            data: components['schemas']['Context'];
        };
        SummaryTime: {
            draft_minutes: number;
            approved_billable_unallocated_minutes: number;
            allocated_to_draft_minutes: number;
        };
        CurrencyAmount: {
            currency: components['schemas']['Currency'];
            amount: number;
        };
        SummaryInvoices: {
            draft_count: number;
            overdue_count: number;
            draft_amounts: components['schemas']['CurrencyAmount'][];
            collectible_balances: components['schemas']['CurrencyAmount'][];
            overdue_balances: components['schemas']['CurrencyAmount'][];
        };
        Summary: {
            workspace_id: components['schemas']['Uuid'];
            active_projects?: number;
            time?: components['schemas']['SummaryTime'];
            invoices?: components['schemas']['SummaryInvoices'];
        };
        SummaryResponse: {
            data: components['schemas']['Summary'];
        };
        Project: {
            id: components['schemas']['Uuid'];
            company_id: components['schemas']['Uuid'];
            company_name: string;
            name: string;
            description: string | null;
            /** @description Canonical host/owner/name this project is worked in, or null when unmapped. Absent entirely for a portal client, who is not shown internal repository names. */
            repository?: string | null;
            status: string;
            is_visible_to_client: boolean;
            version: components['schemas']['Version'];
            /** Format: uri */
            web_url: string;
        };
        ProjectDetail: {
            id: components['schemas']['Uuid'];
            company_id: components['schemas']['Uuid'];
            company_name: string;
            name: string;
            description: string | null;
            /** @description Canonical host/owner/name this project is worked in, or null when unmapped. Absent entirely for a portal client, who is not shown internal repository names. */
            repository?: string | null;
            status: string;
            is_visible_to_client: boolean;
            version: components['schemas']['Version'];
            /** Format: uri */
            web_url: string;
            tasks?: components['schemas']['Task'][];
        };
        ProjectListResponse: {
            data: components['schemas']['Project'][];
            meta: components['schemas']['PaginationMeta'];
        };
        ProjectDetailResponse: {
            data: components['schemas']['ProjectDetail'];
        };
        Task: {
            id: components['schemas']['Uuid'];
            project_id: components['schemas']['Uuid'];
            title: string;
            description: string | null;
            /** @enum {string} */
            status: 'open' | 'in_progress' | 'completed';
            is_visible_to_client: boolean;
            /** Format: date-time */
            completed_at: string | null;
            version: components['schemas']['Version'];
            /** Format: uri */
            web_url: string;
        };
        TaskListResponse: {
            data: components['schemas']['Task'][];
            meta: components['schemas']['PaginationMeta'];
        };
        TaskResponse: {
            data: components['schemas']['Task'];
        };
        TaskCreateRequest: {
            title: string;
            description?: string | null;
            is_visible_to_client?: boolean;
        };
        TaskUpdateRequest: {
            expected_version: components['schemas']['Version'];
            title?: string;
            description?: string | null;
            /** @enum {string} */
            status?: 'open' | 'in_progress' | 'completed';
            is_visible_to_client?: boolean;
        };
        TimeEntry: {
            /**
             * Format: uuid
             * @description Public id of the tenant-owned invoice allocating this time; null when unallocated.
             */
            invoice_id: string | null;
            /**
             * @description No allocation, a draft-invoice reservation, or an allocation to a non-draft invoice. Legacy approved status does not imply unallocated.
             * @enum {string}
             */
            allocation_state: 'unallocated' | 'reserved' | 'consumed';
            id: components['schemas']['Uuid'];
            author_id: components['schemas']['Uuid'];
            project_id: components['schemas']['Uuid'];
            /** Format: uuid */
            task_id: string | null;
            /** Format: date */
            worked_on: string;
            minutes: number;
            description: string | null;
            is_billable: boolean;
            is_deferred: boolean;
            is_visible_to_client: boolean;
            /** @description The text a client reads on the invoice. `description` stays the internal note for anyone on the worker's side of the entry; a portal client receives this text there too and never the internal note. */
            client_visible_description: string | null;
            status: components['schemas']['TimeStatus'];
            version: components['schemas']['Version'];
            /** Format: uri */
            web_url: string;
            billing_rate_amount?: number | null;
            currency?: components['schemas']['Currency'];
            /** @enum {string|null} */
            subcontractor_billing_mode?:
                'flat_hourly' | 'retainer' | 'direct' | null;
            subcontractor_cost_amount?: number | null;
            subcontractor_cost_currency?: string | null;
        };
        TimeEntryListResponse: {
            data: components['schemas']['TimeEntry'][];
            meta: components['schemas']['PaginationMeta'];
        };
        TimeEntryResponse: {
            data: components['schemas']['TimeEntry'];
        };
        TimeEntryBatchResponse: {
            data: components['schemas']['TimeEntry'][];
        };
        TimeLogItem: {
            project_id: components['schemas']['Uuid'];
            /** Format: uuid */
            task_id?: string | null;
            /** Format: date */
            worked_on: string;
            minutes: number;
            description: string;
            is_billable?: boolean;
            is_deferred?: boolean;
            /** @description When omitted, defaults to true if client_visible_description contains text. Send false to keep the entry hidden while staging client text. */
            is_visible_to_client?: boolean;
            /** @description Client-facing text. When supplied without is_visible_to_client, the entry defaults to client-visible. */
            client_visible_description?: string | null;
            /** @description Explicit rate in minor units; requires the time:approve OAuth scope and a user who can approve project time. */
            billing_rate_amount?: number | null;
            currency?: string | null;
        } & unknown;
        TimeLogRequest: {
            entries: components['schemas']['TimeLogItem'][];
            /** @description Approve the logged entries in the same transaction. Requires the time:approve OAuth scope, a user who can approve time on every project, and the agent write cutover; if approval is refused nothing is logged. */
            approve?: boolean;
        };
        TimeUpdateRequest: {
            expected_version: components['schemas']['Version'];
            /** Format: date */
            worked_on?: string;
            minutes?: number;
            description?: string;
            is_billable?: boolean;
            is_deferred?: boolean;
            is_visible_to_client?: boolean;
            client_visible_description?: string | null;
        } & unknown;
        ExpectedVersionRequest: {
            expected_version: components['schemas']['Version'];
        };
        TimeApprovalItem: {
            id: components['schemas']['Uuid'];
            expected_version: components['schemas']['Version'];
            billing_rate_amount?: number;
            currency?: components['schemas']['Currency'];
        };
        TimeApprovalRequest: {
            entries: components['schemas']['TimeApprovalItem'][];
        };
        DeletionReceipt: {
            deleted_id: components['schemas']['Uuid'];
        };
        DeletionResponse: {
            data: components['schemas']['DeletionReceipt'];
        };
        ApprovalReceipt: {
            approved_ids: components['schemas']['Uuid'][];
        };
        ApprovalResponse: {
            data: components['schemas']['ApprovalReceipt'];
        };
        Invoice: {
            id: components['schemas']['Uuid'];
            company_id: components['schemas']['Uuid'];
            invoice_number: string;
            status: components['schemas']['InvoiceStatus'];
            invoice_kind: components['schemas']['InvoiceKind'];
            /** @description True only for an ad-hoc draft, the one kind invoices.update_draft accepts; a generated draft is regenerated instead. */
            editable: boolean;
            linked_time_state: components['schemas']['LinkedTimeState'];
            currency: components['schemas']['Currency'];
            total_amount: number;
            paid_amount: number;
            balance_amount: number;
            /** Format: date */
            issue_date: string | null;
            /** Format: date */
            due_date: string | null;
            version: components['schemas']['Version'];
            /** Format: uri */
            web_url: string;
            /** Format: uri */
            pdf_url: string;
            notes?: string | null;
        };
        InvoiceLine: {
            id: components['schemas']['Uuid'];
            /** Format: uuid */
            project_id: string | null;
            type: string;
            description: string;
            quantity: string;
            unit_amount: number;
            tax_amount: number;
            total_amount: number;
        };
        InvoiceDetail: {
            id: components['schemas']['Uuid'];
            company_id: components['schemas']['Uuid'];
            invoice_number: string;
            status: components['schemas']['InvoiceStatus'];
            invoice_kind: components['schemas']['InvoiceKind'];
            /** @description True only for an ad-hoc draft, the one kind invoices.update_draft accepts; a generated draft is regenerated instead. */
            editable: boolean;
            linked_time_state: components['schemas']['LinkedTimeState'];
            currency: components['schemas']['Currency'];
            total_amount: number;
            paid_amount: number;
            balance_amount: number;
            /** Format: date */
            issue_date: string | null;
            /** Format: date */
            due_date: string | null;
            version: components['schemas']['Version'];
            /** Format: uri */
            web_url: string;
            /** Format: uri */
            pdf_url: string;
            notes?: string | null;
            lines: components['schemas']['InvoiceLine'][];
        };
        InvoiceListResponse: {
            data: components['schemas']['Invoice'][];
            meta: components['schemas']['PaginationMeta'];
        };
        InvoiceDetailResponse: {
            data: components['schemas']['InvoiceDetail'];
        };
        InvoiceMutation: {
            id: components['schemas']['Uuid'];
            status: components['schemas']['InvoiceStatus'];
            linked_time_state: components['schemas']['LinkedTimeState'];
            invoice_number: string;
            version: components['schemas']['Version'];
            /** Format: uri */
            web_url: string;
        };
        /** @description REST returns the invoice mutation shape. MCP returns the invoice exactly as invoices.get does when the token also holds billing:read and invoices.get is enabled, and the mutation shape otherwise. */
        InvoiceIssueResponse: {
            data:
                | components['schemas']['InvoiceDetail']
                | components['schemas']['InvoiceMutation'];
        };
        InvoiceMutationResponse: {
            data: components['schemas']['InvoiceMutation'];
        };
        InvoiceManualLine: {
            /** Format: uuid */
            project_id?: string | null;
            type: string;
            description: string;
            quantity: string | number;
            unit_amount: number;
            tax_amount?: number | null;
        };
        InvoiceCreateRequest: {
            company_id: components['schemas']['Uuid'];
            currency?: string | null;
            /** Format: date */
            due_date?: string | null;
            notes?: string | null;
            time_entry_ids?: components['schemas']['Uuid'][];
            manual_lines?: components['schemas']['InvoiceManualLine'][];
        };
        InvoiceUpdateRequest: {
            expected_version: components['schemas']['Version'];
            currency?: string | null;
            /** Format: date */
            due_date?: string | null;
            notes?: string | null;
            time_entry_ids: components['schemas']['Uuid'][];
            manual_lines: components['schemas']['InvoiceManualLine'][];
        };
        InvoiceIssueRequest: {
            expected_version: components['schemas']['Version'];
            /** @constant */
            confirm: true;
            /** @description Money already received for this draft, recorded in the same transaction so the invoice is issued and paid or not changed at all. Requires the payments:record OAuth scope, a workspace owner/admin, and the payment write cutover; never initiates a charge, refuses overpayment, and cancels the automatic client delivery that issuing schedules. */
            payment?: components['schemas']['InvoiceIssuePayment'];
        };
        InvoiceIssuePayment: {
            amount: number;
            currency: string;
            /** Format: date */
            received_on: string;
            method: string;
            reference?: string | null;
        };
        InvoiceSendRequest: {
            expected_version: components['schemas']['Version'];
            /** @constant */
            confirm: true;
            recipients: string[];
        };
        InvoiceDetailsUpdateRequest: {
            expected_version: components['schemas']['Version'];
            /** Format: date */
            due_date?: string | null;
            notes?: string | null;
        } & (unknown | unknown);
        InvoiceCorrectionLine: {
            id: components['schemas']['Uuid'];
            description: string;
            quantity: string;
            unit_amount: number;
            tax_amount: number;
        };
        InvoiceCorrectionRequest: {
            expected_version: components['schemas']['Version'];
            /** @constant */
            confirm: true;
            reason: string;
            /** Format: date */
            due_date?: string | null;
            lines?: components['schemas']['InvoiceCorrectionLine'][];
        } & (unknown | unknown);
        InvoiceVoidRequest: {
            expected_version: components['schemas']['Version'];
            /** @constant */
            confirm: true;
            reason: string;
        };
        InvoiceDiscardRequest: {
            expected_version: components['schemas']['Version'];
            /** @constant */
            confirm: true;
            reason: string;
        };
    };
    responses: {
        /** @description OAuth, authorization, tenant, conflict, validation, or rate-limit error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': components['schemas']['Error'];
            };
        };
    };
    parameters: {
        ExpenseId: string;
        PaymentId: string;
        WorkspaceId: string;
        ProjectId: string;
        TaskId: string;
        TimeEntryId: string;
        InvoiceId: string;
        TokenId: string;
        Limit: number;
        Cursor: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    'time_entries.unapprove': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                entry_id: components['parameters']['TimeEntryId'];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['ExpectedVersionRequest'];
            };
        };
        responses: {
            /** @description Time approval withdrawn or replayed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['TimeEntryResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'agreements.terminate': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                agreement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['agreements_terminateRequest'];
            };
        };
        responses: {
            /** @description Authorized result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['AgreementResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'agreements.activate': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                agreement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['agreements_activateRequest'];
            };
        };
        responses: {
            /** @description Authorized result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['AgreementResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'agreements.create': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['agreements_createRequest'];
            };
        };
        responses: {
            /** @description Authorized result */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['AgreementResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'agreements.get': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                agreement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['AgreementResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'agreements.update': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                agreement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['agreements_updateRequest'];
            };
        };
        responses: {
            /** @description Authorized result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['AgreementResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'agreements.list': {
        parameters: {
            query?: {
                status?:
                    'draft' | 'active' | 'terminated' | 'expired' | 'paused';
                limit?: components['parameters']['Limit'];
                cursor?: components['parameters']['Cursor'];
            };
            header?: never;
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['AgreementListResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'clients.restore': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['clients_restoreRequest'];
            };
        };
        responses: {
            /** @description Authorized result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ClientCompanyResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'clients.archive': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['clients_archiveRequest'];
            };
        };
        responses: {
            /** @description Authorized result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ClientCompanyResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'clients.get': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ClientCompanyResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'clients.update': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['clients_updateRequest'];
            };
        };
        responses: {
            /** @description Authorized result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ClientCompanyResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'clients.list': {
        parameters: {
            query?: {
                status?: 'active' | 'archived';
                limit?: components['parameters']['Limit'];
                cursor?: components['parameters']['Cursor'];
            };
            header?: never;
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ClientCompanyListResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'clients.create': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['clients_createRequest'];
            };
        };
        responses: {
            /** @description Authorized result */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ClientCompanyResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'expenses.list': {
        parameters: {
            query?: {
                company_id?: string;
                project_id?: string;
                status?: 'draft' | 'approved' | 'invoiced';
                limit?: components['parameters']['Limit'];
                cursor?: components['parameters']['Cursor'];
            };
            header?: never;
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized expenses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ExpenseListResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'expenses.log': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['ExpenseLogRequest'];
            };
        };
        responses: {
            /** @description Draft expenses recorded or replayed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ExpenseBatchResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'expenses.delete': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                expense_id: components['parameters']['ExpenseId'];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['ExpectedVersionRequest'];
            };
        };
        responses: {
            /** @description Draft expense soft-deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['DeletionResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'expenses.update': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                expense_id: components['parameters']['ExpenseId'];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['ExpenseUpdateRequest'];
            };
        };
        responses: {
            /** @description Draft expense updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ExpenseResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'payments.list': {
        parameters: {
            query?: {
                limit?: components['parameters']['Limit'];
                cursor?: components['parameters']['Cursor'];
                invoice_id?: string;
                company_id?: string;
            };
            header?: never;
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized received payments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ReceivedPaymentListResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'payments.record': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['ReceivedPaymentRecordRequest'];
            };
        };
        responses: {
            /** @description Authorized received payments */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ReceivedPaymentBatchResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'payments.correct': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                payment_id: components['parameters']['PaymentId'];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['ReceivedPaymentCorrectionRequest'];
            };
        };
        responses: {
            /** @description Corrected payment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ReceivedPaymentResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'context.get': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized context */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ContextResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'connections.revoke': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components['parameters']['TokenId'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components['responses']['Error'];
        };
    };
    'operations.summary': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role-sensitive summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['SummaryResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'projects.list': {
        parameters: {
            query?: {
                limit?: components['parameters']['Limit'];
                cursor?: components['parameters']['Cursor'];
                status?: 'active' | 'archived' | 'completed';
                query?: string;
            };
            header?: never;
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ProjectListResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'projects.get': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                project_id: components['parameters']['ProjectId'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized project detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ProjectDetailResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'tasks.create': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                project_id: components['parameters']['ProjectId'];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['TaskCreateRequest'];
            };
        };
        responses: {
            /** @description Task created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['TaskResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'tasks.list': {
        parameters: {
            query?: {
                project_id?: string;
                limit?: components['parameters']['Limit'];
                cursor?: components['parameters']['Cursor'];
            };
            header?: never;
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized tasks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['TaskListResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'tasks.get': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                task_id: components['parameters']['TaskId'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized task */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['TaskResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'tasks.update': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                task_id: components['parameters']['TaskId'];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['TaskUpdateRequest'];
            };
        };
        responses: {
            /** @description Task updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['TaskResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'time_entries.list': {
        parameters: {
            query?: {
                project_id?: string;
                status?: components['schemas']['TimeStatus'];
                allocation_state?: 'unallocated' | 'reserved' | 'consumed';
                is_billable?: boolean;
                /** @description When true, selects exactly the approved, priced, billable, non-deferred unallocated work counted by operations.summary. allocation_state alone classifies all rows, including drafts and deferred work. */
                unallocated?: boolean;
                from?: string;
                to?: string;
                limit?: components['parameters']['Limit'];
                cursor?: components['parameters']['Cursor'];
            };
            header?: never;
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized time entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['TimeEntryListResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'time_entries.log': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['TimeLogRequest'];
            };
        };
        responses: {
            /** @description Time entries logged or replayed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['TimeEntryBatchResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'time_entries.delete': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                entry_id: components['parameters']['TimeEntryId'];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['ExpectedVersionRequest'];
            };
        };
        responses: {
            /** @description Draft time soft-deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['DeletionResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'time_entries.update': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                entry_id: components['parameters']['TimeEntryId'];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['TimeUpdateRequest'];
            };
        };
        responses: {
            /** @description Draft time updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['TimeEntryResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'time_entries.approve': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['TimeApprovalRequest'];
            };
        };
        responses: {
            /** @description Time entries approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ApprovalResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'invoices.list': {
        parameters: {
            query?: {
                status?: components['schemas']['InvoiceStatus'];
                limit?: components['parameters']['Limit'];
                cursor?: components['parameters']['Cursor'];
            };
            header?: never;
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized invoices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['InvoiceListResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'invoices.create_draft': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['InvoiceCreateRequest'];
            };
        };
        responses: {
            /** @description Invoice draft created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['InvoiceMutationResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'invoices.get': {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                invoice_id: components['parameters']['InvoiceId'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized invoice with browser payment URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['InvoiceDetailResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'invoices.update_draft': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                invoice_id: components['parameters']['InvoiceId'];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['InvoiceUpdateRequest'];
            };
        };
        responses: {
            /** @description Draft invoice updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['InvoiceMutationResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'invoices.discard_draft': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                invoice_id: components['parameters']['InvoiceId'];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['InvoiceDiscardRequest'];
            };
        };
        responses: {
            /** @description Draft discarded and linked time released */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['InvoiceMutationResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'invoices.issue': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                invoice_id: components['parameters']['InvoiceId'];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['InvoiceIssueRequest'];
            };
        };
        responses: {
            /** @description Invoice issued, and paid when a payment was supplied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['InvoiceIssueResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'invoices.send': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                invoice_id: components['parameters']['InvoiceId'];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['InvoiceSendRequest'];
            };
        };
        responses: {
            /** @description Invoice delivery queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['InvoiceMutationResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'invoices.void': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                invoice_id: components['parameters']['InvoiceId'];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['InvoiceVoidRequest'];
            };
        };
        responses: {
            /** @description Invoice voided */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['InvoiceMutationResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'invoices.update_details': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                invoice_id: components['parameters']['InvoiceId'];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['InvoiceDetailsUpdateRequest'];
            };
        };
        responses: {
            /** @description Draft invoice details updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['InvoiceMutationResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
    'invoices.correct': {
        parameters: {
            query?: never;
            header: {
                'Idempotency-Key': components['parameters']['IdempotencyKey'];
            };
            path: {
                workspace_id: components['parameters']['WorkspaceId'];
                invoice_id: components['parameters']['InvoiceId'];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['InvoiceCorrectionRequest'];
            };
        };
        responses: {
            /** @description Invoice corrected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['InvoiceMutationResponse'];
                };
            };
            default: components['responses']['Error'];
        };
    };
}
