<?php

namespace Tests\Feature\Models;

use App\Models\ClientCompanyMembership;
use App\Models\ClientInvoiceEmailDelivery;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Schema;
use ReflectionClass;
use Tests\TestCase;

/**
 * Every column a model can be asked to write must appear in its fillable list.
 *
 * This exists because the same defect landed five separate times: a migration
 * adds a column, a cast is declared for it, code passes it to `create()`, and
 * Laravel silently drops it. Nothing fails - the write just does not happen, and
 * the field reads as null forever. It cost the recurring-item quantity, the
 * invoice line hours and agreement links, the whole restored invoice ledger, and
 * the time entry rate provenance, each found only when a test happened to look.
 *
 * A column that genuinely should not be mass-assignable belongs in the
 * exemptions below with a reason, so the decision is recorded rather than
 * indistinguishable from an oversight.
 */
final class FillableCoverageTest extends TestCase
{
    use RefreshDatabase;

    /**
     * Columns no model should mass-assign, and why.
     *
     * @var array<string, string>
     */
    private const GLOBALLY_EXEMPT = [
        'id' => 'Database-assigned.',
        'created_at' => 'Managed by Eloquent timestamps.',
        'updated_at' => 'Managed by Eloquent timestamps.',
        'deleted_at' => 'Managed by SoftDeletes.',
        'public_id' => 'Generated by HasPublicId; assigning one would let a caller choose another record\'s identity.',
        'lock_version' => 'Optimistic locking counter; only ever incremented by the persistence layer.',
    ];

    /**
     * Per-model exemptions, and why.
     *
     * @var array<class-string, array<string, string>>
     */
    private const MODEL_EXEMPT = [
        User::class => [
            'email_verified_at' => 'Set by the verification flow, never by user input.',
            'remember_token' => 'Managed by the auth guard.',
            'password' => 'Hashed and set explicitly so a plaintext value can never be assigned by accident.',
        ],
        ClientInvoiceEmailDelivery::class => [
            'external_metadata' => 'Written only by the external importer, which inserts through the query builder rather than Eloquent.',
        ],
        ClientCompanyMembership::class => [
            'workspace_id' => 'Derived from the named company by the model\'s creating hook. A caller that could set it could set it wrongly, and the composite key added in 2026_08_31_000200 would then refuse the write anyway.',
        ],
    ];

    public function test_every_model_can_write_every_column_it_owns(): void
    {
        $gaps = [];

        foreach ($this->models() as $class) {
            $model = new $class;
            $table = $model->getTable();

            if (! Schema::hasTable($table)) {
                continue;
            }

            // A fully guarded model does not use mass assignment at all.
            if ($model->getFillable() === [] && $model->getGuarded() === ['*']) {
                continue;
            }

            $exempt = array_merge(self::GLOBALLY_EXEMPT, self::MODEL_EXEMPT[$class] ?? []);
            $missing = array_diff(Schema::getColumnListing($table), $model->getFillable(), array_keys($exempt));

            if ($missing !== []) {
                $gaps[] = sprintf('%s [%s]: %s', class_basename($class), $table, implode(', ', $missing));
            }
        }

        $this->assertSame([], $gaps, sprintf(
            'These columns exist but cannot be written through the model, so any create() or update() '.
            "passing them discards the value without error.\n\n%s\n\nAdd each to the model's #[Fillable] ".
            "list, or to this test's exemptions with a reason.",
            implode("\n", $gaps),
        ));
    }

    /**
     * Fillable entries that name no column are equally silent - the attribute is
     * simply never persisted, which usually means a rename left one behind.
     */
    public function test_no_model_declares_a_fillable_column_that_does_not_exist(): void
    {
        $ghosts = [];

        foreach ($this->models() as $class) {
            $model = new $class;
            $table = $model->getTable();

            if (! Schema::hasTable($table)) {
                continue;
            }

            $unknown = array_diff($model->getFillable(), Schema::getColumnListing($table));
            if ($unknown !== []) {
                $ghosts[] = sprintf('%s [%s]: %s', class_basename($class), $table, implode(', ', $unknown));
            }
        }

        $this->assertSame([], $ghosts, "Fillable names a column the table does not have:\n".implode("\n", $ghosts));
    }

    /**
     * @return list<class-string<Model>>
     */
    private function models(): array
    {
        $models = [];

        foreach (glob(base_path('app/Models/*.php')) ?: [] as $file) {
            $class = 'App\\Models\\'.basename($file, '.php');
            if (! class_exists($class)) {
                continue;
            }

            $reflection = new ReflectionClass($class);
            if ($reflection->isAbstract() || ! $reflection->isSubclassOf(Model::class)) {
                continue;
            }

            $models[] = $class;
        }

        sort($models);

        return $models;
    }
}
